#! /bin/bash
# echo 1 > /sys/bus/pci/devices/0000:01:00.0/reset
echo 1 > /sys/bus/pci/devices/0000:01:00.0/remove && echo 1 > /sys/bus/pci/devices/0000:01:00.1/remove && echo 1 > /sys/bus/pci/devices/0000:00:01.0/rescan
