#! /bin/bash                                                                                            
case "$1" in
     local)
          arecord -f dat -D plughw:0,0 | ssh -C root@192.168.2.30 aplay -f dat
          ;;
     net)
          arecord -f dat -D plughw:0,0 | ssh -C root@funnyafricashirt.party aplay -f dat
          ;;
     *)
          printf "\nlocal = 192.168.2.30\nnet = funnyafricashirt.party -p 22223\n\n"
          ;;
esac

