#! /bin/bash

photos=( $(ls "/home/brody/storage/pictures/important/sham/montreal-2019" | grep -e "**.HEIC") )

for photo in "${photos[@]}"
do
    /usr/bin/heif-converter "./${photo}" "./${photo%.HEIC}.jpg"
done

echo "Done!"
