#!/bin/bash
backName="$HOSTNAME-$(date +d%d-%b-y%Y-h%H)"
if ! mount | grep "Files-fasp";
then
    ./mount-fasp
fi
backDir=/home/brody/storage/backups/${backName}
mkdir -p ${backDir}
chown brody:brody ${backDir}
chmod 777 ${backDir}
sudo rsync -arAHlXvquKxzP --exclude=Files-fasp --exclude=storage --exclude=raid0 /home ${backDir}/home
sudo rsync -arAHlXvquKxzP /etc ${backDir}/etc
sudo rsync -arAHlXvquKxzP /root ${backDir}/root
sudo rsync -arAHlXvquKxzP /boot ${backDir}/boot
#mkdir -p ${backDir}/var/backups && sudo rsync -arAHlXvquKxzP /var/backups ${backDir}/var/backups
#mkdir -p ${backDir}/var/log && sudo rsync -arAHlXvquKxzP /var/log ${backDir}/var/log


