#! /bin/bash
#ssh root@192.168.2.20 -p 22 -i /home/brody/.ssh/id_ed25519-sayonara
sayonara=192.168.2.20
key="/home/brody/.ssh/id_ed25519-brody"
if hostname -I | grep -q "192.168.2.*"
then
    ssh root@${sayonara} -p 22 -i ${key}
    exit
else
    ssh root@funnyafricashirt.party -p 22222 -i ${key}
    exit
fi
